// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const getTestDatabaseUrl = () => {
  if (process.env.TEST_DATABASE_URL) {
    return process.env.TEST_DATABASE_URL
  }

  if (!process.env.DATABASE_URL) {
    return undefined
  }

  const url = new URL(process.env.DATABASE_URL)
  url.searchParams.set('schema', 'finance_dash_test')

  return url.toString()
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.NODE_ENV === 'test'
      ? getTestDatabaseUrl()
      : process.env["DATABASE_URL"],
  },
});
