-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "isActive" SET DEFAULT true,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
